baseurl = "http://url-to-your-site.com/"
title = "Adventures in Elm"
languageCode = "en-US"
MetaDataFormat = "toml"
theme = "greyshade"

[author]
    name = "Rod Watkins"

[permalinks]

    # Permalink format for pages.
    page = "/:title/"

    # Permalink format for blog posts.
    post = "/article/:title/"

[taxonomies]
category = "categories"
tag = "tags"

[params]
# site description, will show under navigation
description = "Philosopher Programmer"

# RSS / Email (optional) subscription links (change if using something like Feedburner)
subscribe_rss = "/index.xml"
subscribe_email = ""

# social links
facebook_user = "rod.watkins.52"
googleplus_user = ""
twitter_user = "rodwatkins7"
github_user = "rpwatkins"
coderwall_user = ""
stackoverflow_user = ""
stackoverflow_user_id = ""
linkedin_user = ""
pinterest_user = ""
delicious_user = ""
pinboard_user = ""
quora_user = ""
instagram_user = ""
behance_user = ""
douban_user = ""

# share links
facebook_like = true
twitter_tweet_button = true
google_plus_one = "true"
addthis_profile_id = ""

# Disqus Comments
disqus_short_name = "adventuresinelm"
disqus_show_comment_count = false

# google analytics
google_analytics_tracking_id = ""
